# Generated by Django 2.0 on 2020-03-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='Contenue',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='TempsAConsacrer',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
