# Generated by Django 2.0 on 2020-03-21 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0002_auto_20200321_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='Deadline',
            field=models.DateField(default=datetime.datetime(2020, 3, 21, 21, 34, 33, 509180, tzinfo=utc)),
        ),
    ]
