# Generated by Django 2.0 on 2020-03-21 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0003_auto_20200321_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='Deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
