# Generated by Django 2.0 on 2020-03-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0004_auto_20200321_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='DateDeCreation',
            field=models.DateField(auto_now=True),
        ),
    ]
