# Generated by Django 2.0 on 2020-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0005_tache_datedecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='DateDeCreation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
