# Generated by Django 2.0 on 2020-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0008_auto_20200322_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='TempsConsacrer',
            field=models.FloatField(null=True),
        ),
    ]
