# Generated by Django 2.0 on 2020-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0009_tache_tempsconsacrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='TempsAConsacrer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tache',
            name='TempsConsacrer',
            field=models.FloatField(default=0.0),
        ),
    ]
