# Generated by Django 2.0 on 2020-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0011_tempvar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempvar',
            old_name='Etat',
            new_name='PauseouPlay',
        ),
        migrations.AddField(
            model_name='tache',
            name='PauseouPlay',
            field=models.TextField(default='pause'),
        ),
    ]
