# Generated by Django 2.0 on 2020-03-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0012_auto_20200328_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='PauseouPlay',
            field=models.IntegerField(default=0),
        ),
    ]
