# Generated by Django 2.0 on 2020-03-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0013_auto_20200328_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempvar',
        ),
    ]
