# Generated by Django 2.0 on 2020-03-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0014_delete_tempvar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='TempsTemp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
