# Generated by Django 2.0 on 2020-03-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0015_tache_tempstemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheTemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TempsList', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tache',
            name='TempsCle',
            field=models.IntegerField(null=True),
        ),
    ]
