# Generated by Django 2.0 on 2020-03-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0017_auto_20200329_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='TempsCle',
            field=models.TextField(default=''),
        ),
    ]
