# Generated by Django 2.0 on 2020-04-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0019_faussebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='Priorite',
            field=models.CharField(choices=[('non important , non urgent', 0), (' important ,  non urgent', 1), ('non important , urgent', 2), ('import tant , urgent', 3)], default=0, max_length=2),
        ),
    ]
