# Generated by Django 2.0 on 2020-04-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0021_auto_20200404_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='Priorite',
            field=models.IntegerField(choices=[(0, 'non important , non urgent'), (1, ' important ,  non urgent'), (2, 'non important , urgent'), (3, 'import tant , urgent')], default=0, max_length=2),
        ),
    ]
