# Generated by Django 2.0 on 2020-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0022_auto_20200404_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='FinishDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
