# Generated by Django 3.0.3 on 2020-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0023_tache_finishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='Priorite',
            field=models.IntegerField(choices=[(0, 'non important , non urgent'), (1, ' important ,  non urgent'), (2, 'non important , urgent'), (3, 'import tant , urgent')], default=0),
        ),
    ]
