# Generated by Django 3.0.3 on 2020-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0028_auto_20200903_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='TempsAConsacrer',
            field=models.DurationField(),
        ),
    ]
