# Generated by Django 3.0.3 on 2020-09-04 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0029_auto_20200903_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='TempsConsacrer',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
