# Generated by Django 3.0.3 on 2020-09-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0030_auto_20200904_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='TempsRestant',
            field=models.DurationField(null=True),
        ),
    ]
