# Generated by Django 3.0.3 on 2020-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache_app', '0031_tache_tempsrestant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempsDeTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deltaTemps', models.DurationField()),
                ('day', models.DateTimeField()),
            ],
        ),
    ]
